# Generated by Django 3.2.5 on 2021-07-10 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_pedidos_produtos_venda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='price',
            field=models.CharField(max_length=100),
        ),
    ]
