# Generated by Django 3.2.5 on 2021-07-11 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_categoria_contato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='valor',
            field=models.IntegerField(),
        ),
    ]
