# Generated by Django 3.2.5 on 2021-07-11 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_pedidos_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='valor',
            field=models.IntegerField(null=True),
        ),
    ]
