# Generated by Django 3.2.5 on 2021-07-11 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210711_0338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidos',
            name='numero_pedido',
        ),
    ]
