# Generated by Django 3.2.5 on 2021-07-11 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_pedidos_numero_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='item',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='quantidade',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='usuario',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='valor',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
