# Generated by Django 3.2.5 on 2021-07-12 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20210711_2018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='modelo',
        ),
        migrations.AddField(
            model_name='venda',
            name='total',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
