# Generated by Django 3.2.5 on 2021-07-12 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20210711_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='total',
            field=models.FloatField(),
        ),
    ]
