# Generated by Django 3.2.5 on 2021-07-12 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_venda_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='valor',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
