# Generated by Django 3.2.5 on 2021-07-12 22:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0013_alter_pedidos_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='Pessoa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='valor',
            field=models.IntegerField(null=True),
        ),
    ]
