# Generated by Django 3.2.5 on 2021-07-13 04:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0016_auto_20210713_0102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidos',
            name='venda_id',
        ),
        migrations.CreateModel(
            name='itens_vendido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(blank=True, max_length=100, null=True)),
                ('valor', models.IntegerField(null=True)),
                ('quantidade', models.CharField(blank=True, max_length=100, null=True)),
                ('venda_id', models.IntegerField(null=True)),
                ('Pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
